version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:80"
        networks:
            - lab-net
            
networks:
    lab-net:
        driver: bridge